name: Start flask
on:
  push:
    branches:
      - master
jobs:
  launch-flask-server:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: ./.github/actions/ngrok_action
        id: ngrok
        with:
            ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
            timeout: '1h'
            tunnel_type: 'http'
            port: 5000
            save_url_to_filename: 'ngrok_url.txt'
      - name: Start flask server
        run: ( python app.py > /dev/null 2>&1 ) &
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ngrok-url
          path: ngrok_url.txt
      - name: Configure Git
        run: |
          git config user.email "YOUR_EMAIL@EMAIL.COM"
          git config user.name "YOUR NAME"
      - name: Create Empty Commit
        run: |
          git checkout dev
          git commit --allow-empty -m "Empty commit"
          git push origin dev
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
