name: Check Submodule Updates

on:
  push:
    branches:
      - master
jobs:
  check-submodules:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Make sure to fetch submodules
          submodules: 'recursive'

      - name: Setup Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - name: Check for submodule updates
        run: |
          SUBMODULE_BRANCH="main"
          url=https://a3c4-136-38-129-161.ngrok-free.app/

          # Navigate to the submodule directory
          cd ./tmp
          echo "Entering submodule directory..."

          git fetch

          LOCAL_COMMIT=$(git rev-parse HEAD)
          REMOTE_COMMIT=$(git rev-parse origin/${SUBMODULE_BRANCH})
          if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
            echo "Submodule in branch ${SUBMODULE_BRANCH} has been updated."
            curl --header "Content-Type: application/json"   --request POST   --data '{"package": "swig"}'   $url
            exit 1
          else
            echo "No updates found for submodule in branch ${SUBMODULE_BRANCH}."
          fi

