name: Check Submodule Updates

on:
  push:
    branches:
      - dev
jobs:
  launch-flask-server:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: ./.github/actions/ngrok_action
        id: ngrok
        with:
            ngrok_authtoken: ${{ secrets.NGROK_AUTHTOKEN }}
            timeout: '1h'
            tunnel_type: 'http'
            port: 5000
            save_url_to_filename: 'ngrok_url.txt'
      - name: Start flask server
        run: ( python app.py > /dev/null 2>&1 ) &
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: ngrok-url
          path: ngrok_url.txt
  check-submodules:
    runs-on: ubuntu-latest
    needs: launch-flask-server
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: ngrok-url
      - name: Print ngrok url
        run: |
          echo "NGROK_URL=$(cat ngrok_url.txt)" >> $GITHUB_ENV
          echo ${{ env.NGROK_URL }}
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          # Make sure to fetch submodules
          submodules: 'recursive'
      - name: Setup Git
        run: |
          sudo apt-get update
          sudo apt-get install -y git
      - name: Check for submodule updates
        run: |
          SUBMODULE_BRANCH="main"
          # Navigate to the submodule directory
          cd ./tmp
          echo "Entering submodule directory..."

          git fetch

          LOCAL_COMMIT=$(git rev-parse HEAD)
          REMOTE_COMMIT=$(git rev-parse origin/${SUBMODULE_BRANCH})
          if [ "$LOCAL_COMMIT" != "$REMOTE_COMMIT" ]; then
            echo "Submodule in branch ${SUBMODULE_BRANCH} has been updated."
            curl --header "Content-Type: application/json"   --request POST   --data '{"package": "swig"}' ${{ env.NGROK_URL }} 
            exit 1
          else
            echo "No updates found for submodule in branch ${SUBMODULE_BRANCH}."
          fi

